-- ARCs (bots) do arc-data.js -> tabela public.arcs
-- Idempotente: ON CONFLICT DO UPDATE (upsert por id).
-- As imagens ficam em /assets/bots/<id>.png (servidas como arquivos estaticos)

insert into public.arcs
  (id, name, name_en, description, description_en, type, threat, weakness, weakness_en, destroy_xp, loot_xp, drops, image_url, active)
values
  ('arc_bastion', 'BASTION', 'BASTION', 'Massive, crab-like machines that are slow but devastating. They''re capable of shredding shields and dealing massive damage with heavy attacks.', 'Massive, crab-like machines that are slow but devastating. They''re capable of shredding shields and dealing massive damage with heavy attacks.', 'Heavy Assault', 'Critical', 'Destroy the canister on his rear, to expose it''s weakpoint.', 'Destroy the canister on his rear, to expose it''s weakpoint.', 500, 250, '["arc_alloy","arc_powercell","arc_motion_core","arc_circuitry","bastion_cell"]'::jsonb, '/assets/bots/arc_bastion.png', true),
  ('arc_bombardier', 'BOMBARDIER', 'BOMBARDIER', 'A massive artillery unit designed for long-range bombardment. Equipped with devastating explosive capabilities and heavy armor, it can rain destruction from great distances.', 'A massive artillery unit designed for long-range bombardment. Equipped with devastating explosive capabilities and heavy armor, it can rain destruction from great distances.', 'Heavy Artillery', 'Critical', 'Shooting at the yellow rear canister deals direct damage to it''s core.', 'Shooting at the yellow rear canister deals direct damage to it''s core.', 500, 300, '["arc_alloy","advanced_arc_powercell","bombardier_cell","launcher_ammo"]'::jsonb, '/assets/bots/arc_bombardier.png', true),
  ('arc_fireball', 'FIREBALL', 'FIREBALL', 'Small armored rolling ARC that spits flame. Opens front panel when near Raiders to burn them alive, exposing its soft core.', 'Small armored rolling ARC that spits flame. Opens front panel when near Raiders to burn them alive, exposing its soft core.', 'Area Denial', 'High', 'Exposes it''s core, when it''s using the flamethrower.', 'Exposes it''s core, when it''s using the flamethrower.', 100, 100, '["arc_alloy","arc_powercell","fireball_burner"]'::jsonb, '/assets/bots/arc_fireball.png', true),
  ('arc_hornet', 'HORNET', 'HORNET', 'Medium-class drone with armored rotors. It fires focused, high-speed projectiles with a brief red laser warning. Designed to shred shields and light armor.', 'Medium-class drone with armored rotors. It fires focused, high-speed projectiles with a brief red laser warning. Designed to shred shields and light armor.', 'Medium Drone', 'High', 'Unarmored rear thrusters.', 'Unarmored rear thrusters.', 150, 250, '["arc_alloy","arc_powercell","hornet_driver","simple_gun_parts","medium_ammo"]'::jsonb, '/assets/bots/arc_hornet.png', true),
  ('arc_leaper', 'LEAPER', 'LEAPER', 'Massive, arachnid-like siege engine with heavy armor and gravity-defying leap ability. Can clear impossible gaps and reach high vantage points.', 'Massive, arachnid-like siege engine with heavy armor and gravity-defying leap ability. Can clear impossible gaps and reach high vantage points.', 'Siege Engine', 'Critical', 'Fire is most effective. Additionally you can shoot into it''s eye.', 'Fire is most effective. Additionally you can shoot into it''s eye.', 500, 500, '["advanced_arc_powercell","arc_alloy","arc_circuitry","arc_flex_rubber","arc_motion_core","arc_performance_steel","arc_powercell","explosive_compound","leaper_pulse_unit","mechanical_components"]'::jsonb, '/assets/bots/arc_leaper.png', true),
  ('arc_matriarch', 'MATRIARCH', 'MATRIARCH', 'The Matriarch is an imposing ARC machine that makes the Queen look friendly and can be found during a specific map condition.', 'The Matriarch is an imposing ARC machine that makes the Queen look friendly and can be found during a specific map condition.', 'Boss', 'Extreme', 'Central glowing core, which becomes exposed when it attacks. Leg joints are vulnerable too, as well as the red areas on the crown.', 'Central glowing core, which becomes exposed when it attacks. Leg joints are vulnerable too, as well as the red areas on the crown.', 1000, 500, '["arc_alloy","arc_circuitry","arc_performance_steel","advanced_arc_powercell","arc_flex_rubber","arc_synthetic_resin","magnetic_accelerator","matriarch_reactor"]'::jsonb, '/assets/bots/arc_matriarch.png', true),
  ('arc_pop', 'POP', 'POP', 'Small explosive ARC that detonates when approached. Quick elimination required to prevent area damage.', 'Small explosive ARC that detonates when approached. Quick elimination required to prevent area damage.', 'Explosive', 'Moderate', 'Just shoot it.', 'Just shoot it.', 50, 100, '["arc_alloy","arc_powercell","arc_thermo_lining","crude_explosives","pop_trigger"]'::jsonb, '/assets/bots/arc_pop.png', true),
  ('arc_rocketeer', 'ROCKETEER', 'ROCKETEER', 'A formidable flying ARC that dominates airspace with powerful rocket attacks and devastating area-of-effect damage. Designed to saturate areas with explosions.', 'A formidable flying ARC that dominates airspace with powerful rocket attacks and devastating area-of-effect damage. Designed to saturate areas with explosions.', 'Flying Artillery', 'Critical', 'Destroy two thrusters or shoot it''s core, which is located underneath it.', 'Destroy two thrusters or shoot it''s core, which is located underneath it.', 500, 500, '["arc_alloy","arc_powercell","arc_motion_core","arc_circuitry","advanced_arc_powercell","heavy_gun_parts","rocketeer_driver","heavy_ammo"]'::jsonb, '/assets/bots/arc_rocketeer.png', true),
  ('arc_sentinel', 'SENTINEL', 'SENTINEL', 'Stationary but deadly turrets that perch on high vantage points. They scan for targets with long-range precision and lock onto players from a distance.', 'Stationary but deadly turrets that perch on high vantage points. They scan for targets with long-range precision and lock onto players from a distance.', 'Sniper Turret', 'High', 'The yellow unarmored canister will be your main target.', 'The yellow unarmored canister will be your main target.', 200, 300, '["arc_alloy","arc_powercell","arc_coolant","arc_synthetic_resin","arc_thermo_lining","arc_motion_core","sentinel_firing_core","heavy_ammo"]'::jsonb, '/assets/bots/arc_sentinel.png', true),
  ('arc_shredder', 'SHREDDER', 'SHREDDER', 'The Shredder appears in Stella Montis, challenging Raiders to stay sharp in close-quarter encounters.', 'The Shredder appears in Stella Montis, challenging Raiders to stay sharp in close-quarter encounters.', 'Area Denial', 'High', 'Primary weakness is the ''eye-bar'' at it''s head. You may see the orange core between it''s armour plates, which you can shoot too.', 'Primary weakness is the ''eye-bar'' at it''s head. You may see the orange core between it''s armour plates, which you can shoot too.', 200, 250, '["arc_alloy","arc_powercell","shredder_gyro","shotgun_ammo"]'::jsonb, '/assets/bots/arc_shredder.png', true),
  ('arc_snitch', 'SNITCH', 'SNITCH', 'A swift, unarmored scout drone with three rotors. While fragile, it acts as an aerial alarm system, calling in reinforcements when it spots Raiders.', 'A swift, unarmored scout drone with three rotors. While fragile, it acts as an aerial alarm system, calling in reinforcements when it spots Raiders.', 'Scout Drone', 'Moderate', 'Thrusters or the underside plating.', 'Thrusters or the underside plating.', 100, 200, '["arc_alloy","arc_powercell","arc_synthetic_resin","sensors","snitch_scanner"]'::jsonb, '/assets/bots/arc_snitch.png', true),
  ('arc_spotter', 'SPOTTER', 'SPOTTER', 'Spotters are flying support drones for the Bombardier. They will point a laser at any Raider in line-of-sight so the Bombardier can accurately target them. If both Spotters are destroyed a new pair will respawn. When the Bombardier is destroyed the Spotters will fly away.', 'Spotters are flying support drones for the Bombardier. They will point a laser at any Raider in line-of-sight so the Bombardier can accurately target them. If both Spotters are destroyed a new pair will respawn. When the Bombardier is destroyed the Spotters will fly away.', 'Scout Drone', 'High', 'Unarmored thrusters', 'Unarmored thrusters', 100, 200, '["spotter_relay","arc_alloy","arc_powercell","sensors"]'::jsonb, '/assets/bots/arc_spotter.png', true),
  ('arc_surveyor', 'SURVEYOR', 'SURVEYOR', 'The largest of the rolling ARC. It stops periodically to transmit signals. Rarely attacks, usually runs away from Raiders. Breaks into many pieces as damage is taken.', 'The largest of the rolling ARC. It stops periodically to transmit signals. Rarely attacks, usually runs away from Raiders. Breaks into many pieces as damage is taken.', 'Reconnaissance', 'Low', 'Exposes his energy core when shooting his blue beam into the sky.', 'Exposes his energy core when shooting his blue beam into the sky.', 200, 300, '["arc_alloy","arc_powercell","arc_motion_core","arc_circuitry","surveyor_vault"]'::jsonb, '/assets/bots/arc_surveyor.png', true),
  ('arc_the_queen', 'THE QUEEN', 'THE QUEEN', 'A colossal machine deployed during Harvester Events. It''s the Goliath of the ARC forces with incredible durability and lethal arsenal. Requires full squad coordination.', 'A colossal machine deployed during Harvester Events. It''s the Goliath of the ARC forces with incredible durability and lethal arsenal. Requires full squad coordination.', 'Boss', 'Extreme', 'The yellow joints on her legs. Exposes her core when firing the laser.', 'The yellow joints on her legs. Exposes her core when firing the laser.', 1000, 1000, '["arc_alloy","advanced_arc_powercell","arc_motion_core","arc_circuitry","arc_coolant","arc_flex_rubber","arc_thermo_lining","arc_synthetic_resin","arc_performance_steel","advanced_mechanical_components","advanced_electrical_components","complex_gun_parts","magnetic_accelerator","queen_reactor"]'::jsonb, '/assets/bots/arc_the_queen.png', true),
  ('arc_tick', 'TICK', 'TICK', 'Small, spider-like robots that leap onto players, attaching themselves to your head. They''re fast and disorienting, designed to punish careless Raiders.', 'Small, spider-like robots that leap onto players, attaching themselves to your head. They''re fast and disorienting, designed to punish careless Raiders.', 'Ambush Predator', 'Moderate', 'Just shoot it. It''s also one-hit with your melee weapon.', 'Just shoot it. It''s also one-hit with your melee weapon.', 50, 100, '["arc_alloy","tick_pod"]'::jsonb, '/assets/bots/arc_tick.png', true),
  ('arc_turret', 'TURRET', 'TURRET', 'Small, unarmored turret providing close-quarters defense. Mounted on interior walls, it scans for movement and unleashes rapid fire when it spots Raiders.', 'Small, unarmored turret providing close-quarters defense. Mounted on interior walls, it scans for movement and unleashes rapid fire when it spots Raiders.', 'Defense System', 'Moderate', 'Unarmored. Shooting it is enough.', 'Unarmored. Shooting it is enough.', 100, 200, '["arc_alloy","light_ammo","simple_gun_parts"]'::jsonb, '/assets/bots/arc_turret.png', true),
  ('arc_wasp', 'WASP', 'WASP', 'Flying, drone-like robots equipped with powerful machine guns. They operate in swarms, are fast, agile, and relentless. Their buzzing and screeching audio cues are your first warning.', 'Flying, drone-like robots equipped with powerful machine guns. They operate in swarms, are fast, agile, and relentless. Their buzzing and screeching audio cues are your first warning.', 'Flying Drone', 'Moderate', 'Unarmored thrusters.', 'Unarmored thrusters.', 100, 200, '["arc_alloy","arc_powercell","wasp_driver","light_ammo"]'::jsonb, '/assets/bots/arc_wasp.png', true)
on conflict (id) do update set
  name        = excluded.name,
  name_en     = excluded.name_en,
  description = excluded.description,
  description_en = excluded.description_en,
  type        = excluded.type,
  threat      = excluded.threat,
  weakness    = excluded.weakness,
  weakness_en = excluded.weakness_en,
  destroy_xp  = excluded.destroy_xp,
  loot_xp     = excluded.loot_xp,
  drops       = excluded.drops,
  image_url   = excluded.image_url,
  active      = excluded.active;
