-- Popula a tabela arcs com os dados dos inimigos do arc-data.js.
-- name/name_en ficam em inglês por agora (MetaForge sync sobrescreve com tradução).
-- drops usa os IDs do arc-data (mesmos IDs do catalog_items vindo do MetaForge).
-- ON CONFLICT DO NOTHING — idempotente.

insert into public.arcs
  (id, name, name_en, description, description_en, type, threat,
   weakness, weakness_en, destroy_xp, loot_xp, drops, icon_url, active, synced_at)
values

('arc_bastion', 'BASTION', 'BASTION',
 'Máquinas massivas em forma de caranguejo, lentas mas devastadoras. Capazes de destruir escudos e causar dano maciço com ataques pesados.',
 'Massive, crab-like machines that are slow but devastating. They''re capable of shredding shields and dealing massive damage with heavy attacks.',
 'Heavy Assault', 'Critical',
 'Destrua o recipiente traseiro para expor o ponto fraco.',
 'Destroy the canister on his rear, to expose it''s weakpoint.',
 500, 250,
 '["arc_alloy","arc_powercell","arc_motion_core","arc_circuitry","bastion_cell"]'::jsonb,
 '/assets/bots/arc_bastion.png', true, now()),

('arc_bombardier', 'BOMBARDIER', 'BOMBARDIER',
 'Unidade de artilharia pesada para bombardeio de longo alcance. Armadura robusta e capacidade explosiva devastadora.',
 'A massive artillery unit designed for long-range bombardment. Equipped with devastating explosive capabilities and heavy armor.',
 'Heavy Artillery', 'Critical',
 'Atire no recipiente amarelo traseiro para atingir o núcleo diretamente.',
 'Shooting at the yellow rear canister deals direct damage to it''s core.',
 500, 300,
 '["arc_alloy","advanced_arc_powercell","bombardier_cell","launcher_ammo"]'::jsonb,
 '/assets/bots/arc_bombardier.png', true, now()),

('arc_fireball', 'FIREBALL', 'FIREBALL',
 'Pequeno ARC blindado que cospe chamas. Abre o painel frontal para queimar Raiders, expondo seu núcleo vulnerável.',
 'Small armored rolling ARC that spits flame. Opens front panel when near Raiders to burn them alive, exposing its soft core.',
 'Area Denial', 'High',
 'O núcleo fica exposto quando usa o lança-chamas.',
 'Exposes it''s core, when it''s using the flamethrower.',
 100, 100,
 '["arc_alloy","arc_powercell","fireball_burner"]'::jsonb,
 '/assets/bots/arc_fireball.png', true, now()),

('arc_hornet', 'HORNET', 'HORNET',
 'Drone médio com rotores blindados. Dispara projéteis de alta velocidade com aviso de laser vermelho.',
 'Medium-class drone with armored rotors. It fires focused, high-speed projectiles with a brief red laser warning.',
 'Medium Drone', 'High',
 'Propulsores traseiros sem blindagem.',
 'Unarmored rear thrusters.',
 150, 250,
 '["arc_alloy","arc_powercell","hornet_driver","simple_gun_parts","medium_ammo"]'::jsonb,
 '/assets/bots/arc_hornet.png', true, now()),

('arc_leaper', 'LEAPER', 'LEAPER',
 'Massiva máquina de cerco tipo aranha com blindagem pesada e salto gravitacional. Alcança posições impossíveis.',
 'Massive, arachnid-like siege engine with heavy armor and gravity-defying leap ability.',
 'Siege Engine', 'Critical',
 'Fogo é mais eficaz. Atire no olho do inimigo.',
 'Fire is most effective. Additionally you can shoot into it''s eye.',
 500, 500,
 '["advanced_arc_powercell","arc_alloy","arc_circuitry","arc_flex_rubber","arc_motion_core","arc_performance_steel","arc_powercell","explosive_compound","leaper_pulse_unit","mechanical_components"]'::jsonb,
 '/assets/bots/arc_leaper.png', true, now()),

('arc_matriarch', 'MATRIARCH', 'MATRIARCH',
 'Imponente máquina ARC encontrada durante condições especiais de mapa.',
 'The Matriarch is an imposing ARC machine that makes the Queen look friendly and can be found during a specific map condition.',
 'Boss', 'Extreme',
 'Núcleo central exposto durante ataques. Articulações das pernas e áreas vermelhas da coroa.',
 'Central glowing core, which becomes exposed when it attacks. Leg joints are vulnerable too, as well as the red areas on the crown.',
 1000, 500,
 '["arc_alloy","arc_circuitry","arc_performance_steel","advanced_arc_powercell","arc_flex_rubber","arc_synthetic_resin","magnetic_accelerator","matriarch_reactor"]'::jsonb,
 '/assets/bots/arc_matriarch.png', true, now()),

('arc_pop', 'POP', 'POP',
 'Pequeno ARC explosivo que detona ao se aproximar. Elimine rapidamente para evitar dano em área.',
 'Small explosive ARC that detonates when approached. Quick elimination required to prevent area damage.',
 'Explosive', 'Moderate',
 'Só atirar nele.',
 'Just shoot it.',
 50, 100,
 '["arc_alloy","arc_powercell","arc_thermo_lining","crude_explosives","pop_trigger"]'::jsonb,
 '/assets/bots/arc_pop.png', true, now()),

('arc_rocketeer', 'ROCKETEER', 'ROCKETEER',
 'ARC voador formidável que domina o espaço aéreo com ataques de foguete e dano em área devastador.',
 'A formidable flying ARC that dominates airspace with powerful rocket attacks and devastating area-of-effect damage.',
 'Flying Artillery', 'Critical',
 'Destrua os dois propulsores ou atire no núcleo embaixo.',
 'Destroy two thrusters or shoot it''s core, which is located underneath it.',
 500, 500,
 '["arc_alloy","arc_powercell","arc_motion_core","arc_circuitry","advanced_arc_powercell","heavy_gun_parts","rocketeer_driver","heavy_ammo"]'::jsonb,
 '/assets/bots/arc_rocketeer.png', true, now()),

('arc_sentinel', 'SENTINEL', 'SENTINEL',
 'Torretas estacionárias mas letais em pontos altos. Varrem alvos com precisão de longo alcance.',
 'Stationary but deadly turrets that perch on high vantage points. They scan for targets with long-range precision.',
 'Sniper Turret', 'High',
 'O recipiente amarelo sem blindagem é o alvo principal.',
 'The yellow unarmored canister will be your main target.',
 200, 300,
 '["arc_alloy","arc_powercell","arc_coolant","arc_synthetic_resin","arc_thermo_lining","arc_motion_core","sentinel_firing_core","heavy_ammo"]'::jsonb,
 '/assets/bots/arc_sentinel.png', true, now()),

('arc_shredder', 'SHREDDER', 'SHREDDER',
 'Aparece em Stella Montis. Desafiador em combate corpo a corpo.',
 'The Shredder appears in Stella Montis, challenging Raiders to stay sharp in close-quarter encounters.',
 'Area Denial', 'High',
 'Ponto fraco principal é a barra do olho. O núcleo laranja entre as placas de armadura também pode ser atingido.',
 'Primary weakness is the ''eye-bar'' at it''s head. You may see the orange core between it''s armour plates.',
 200, 250,
 '["arc_alloy","arc_powercell","shredder_gyro","shotgun_ammo"]'::jsonb,
 '/assets/bots/arc_shredder.png', true, now()),

('arc_snitch', 'SNITCH', 'SNITCH',
 'Drone de reconhecimento ágil e desarmado. Age como sistema de alarme aéreo, chamando reforços ao avistar Raiders.',
 'A swift, unarmored scout drone with three rotors. Acts as an aerial alarm system, calling in reinforcements when it spots Raiders.',
 'Scout Drone', 'Moderate',
 'Propulsores ou a placa inferior.',
 'Thrusters or the underside plating.',
 100, 200,
 '["arc_alloy","arc_powercell","arc_synthetic_resin","sensors","snitch_scanner"]'::jsonb,
 '/assets/bots/arc_snitch.png', true, now()),

('arc_spotter', 'SPOTTER', 'SPOTTER',
 'Drone de suporte do Bombardier. Aponta laser em Raiders para que o Bombardier os atinja com precisão.',
 'Flying support drones for the Bombardier. They will point a laser at any Raider in line-of-sight so the Bombardier can accurately target them.',
 'Scout Drone', 'High',
 'Propulsores sem blindagem.',
 'Unarmored thrusters.',
 100, 200,
 '["spotter_relay","arc_alloy","arc_powercell","sensors"]'::jsonb,
 '/assets/bots/arc_spotter.png', true, now()),

('arc_surveyor', 'SURVEYOR', 'SURVEYOR',
 'O maior dos ARCs rolantes. Para periodicamente para transmitir sinais. Raramente ataca, geralmente foge.',
 'The largest of the rolling ARC. It stops periodically to transmit signals. Rarely attacks, usually runs away from Raiders.',
 'Reconnaissance', 'Low',
 'Expõe o núcleo de energia ao disparar o feixe azul no céu.',
 'Exposes his energy core when shooting his blue beam into the sky.',
 200, 300,
 '["arc_alloy","arc_powercell","arc_motion_core","arc_circuitry","surveyor_vault"]'::jsonb,
 '/assets/bots/arc_surveyor.png', true, now()),

('arc_the_queen', 'THE QUEEN', 'THE QUEEN',
 'Máquina colossal implantada durante Eventos Colheitadeira. Requer coordenação total do esquadrão.',
 'A colossal machine deployed during Harvester Events. Requires full squad coordination.',
 'Boss', 'Extreme',
 'Articulações amarelas das pernas. Expõe o núcleo ao disparar o laser.',
 'The yellow joints on her legs. Exposes her core when firing the laser.',
 1000, 1000,
 '["arc_alloy","advanced_arc_powercell","arc_motion_core","arc_circuitry","arc_coolant","arc_flex_rubber","arc_thermo_lining","arc_synthetic_resin","arc_performance_steel","advanced_mechanical_components","advanced_electrical_components","complex_gun_parts","magnetic_accelerator","queen_reactor"]'::jsonb,
 '/assets/bots/arc_the_queen.png', true, now()),

('arc_tick', 'TICK', 'TICK',
 'Pequenos robôs tipo aranha que saltam nos jogadores e se prendem à cabeça. Rápidos e desorientadores.',
 'Small, spider-like robots that leap onto players, attaching themselves to your head. They''re fast and disorienting.',
 'Ambush Predator', 'Moderate',
 'Só atirar. Uma pancada de corpo a corpo derruba com um golpe.',
 'Just shoot it. It''s also one-hit with your melee weapon.',
 50, 100,
 '["arc_alloy","tick_pod"]'::jsonb,
 '/assets/bots/arc_tick.png', true, now()),

('arc_turret', 'TURRET', 'TURRET',
 'Pequena torreta sem blindagem para defesa em curto alcance. Montada em paredes internas.',
 'Small, unarmored turret providing close-quarters defense. Mounted on interior walls.',
 'Defense System', 'Moderate',
 'Sem blindagem. Só atirar.',
 'Unarmored. Shooting it is enough.',
 100, 200,
 '["arc_alloy","light_ammo","simple_gun_parts"]'::jsonb,
 '/assets/bots/arc_turret.png', true, now()),

('arc_wasp', 'WASP', 'WASP',
 'Robôs voadores tipo drone equipados com metralhadoras. Operam em enxames, rápidos e implacáveis.',
 'Flying, drone-like robots equipped with powerful machine guns. They operate in swarms, are fast, agile, and relentless.',
 'Flying Drone', 'Moderate',
 'Propulsores sem blindagem.',
 'Unarmored thrusters.',
 100, 200,
 '["arc_alloy","arc_powercell","wasp_driver","light_ammo"]'::jsonb,
 '/assets/bots/arc_wasp.png', true, now())

on conflict (id) do nothing;
